### PR TITLE
Metaverse Mastercard

### PR DESCRIPTION
**Pull request by systwo**
New website design including early access page, various misc updates, introduction of Metaverse Mastercard brand etc.

To be merged only when approved by business as needs to be planned in conjunction with the press release.

### CODE REVIEW

**Comment by javcode** [comment]
can we remove the font files from the repo? There must be a way to get them from a CDN instead. We should not upload big binary files to the repo. Plus their size is 3mb each

**Comment by giraffecrackers** [comment]
image
looks a bit weird on narrow screen

**Comment by javcode** [comment]
are the team avatars used at all for anything? If they are not, they should be removed

**Comment by giraffecrackers** [comment]
i noticed some font files here
As i remember we decided not to include font files for our code

**Comment by systwo** [comment]
> are the team avatars used at all for anything? If they are not, they should be removed

@javcode They are displayed in the main page under 'team'

> image looks a bit weird on narrow screen

@giraffecrackers 

If you can edit to remove the "Get early access" button at anything below medium (as user can use the hamburger to get there). I had a go with `collapse md:visible`but not behaving how I expected

Also need to get the hamburger to retain it's size regardless of screen width

**Comment by javcode** [comment]
are you guys having the same issue?

Screen Shot 2022-10-20 at 3 52 08 PM

Looks like an image is missing?

**Comment by systwo** [comment]
> are you guys having the same issue?
> 
> Screen Shot 2022-10-20 at 3 52 08 PM
> 
> Looks like an image is missing?

No, I see the image just fine. I'll update the alt text though

**Comment by systwo** [comment]
> > are you guys having the same issue?
> > Screen Shot 2022-10-20 at 3 52 08 PM
> > Looks like an image is missing?
> 
> No, I see the image just fine. I'll update the alt text though

Okay... ah yeah, it hasn't made it into the repo... working on it

**Review by giraffecrackers — APPROVED** [review]

**Comment by javcode** [comment]
@systwo FYI, once the PR is merged, a deployment to PROD will happen. So I would say to leave the merge to next Tuesday just in case

**Pull request merged**
